import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Faang investing",
  description: "Generated by Faang investing",
  icons: {
    icon: "/faang.png", // /public path
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="shortcut icon" href="/faang.png" />
      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
